version: '3'
services:
  baarcari:
    platform: linux/amd64
    image: "baarcari:0.1.0"
    container_name: "baarcari"
    build:
      context: ./app
      dockerfile: Dockerfile
    command: bundle exec rackup -p 4567 -o 0.0.0.0
    ports:
      - 4567:4567
    volumes:
      - ./app:/usr/src/app:cached
